//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyAccounting.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContractPayment { get; set; }
        public Nullable<int> ContractStartDate { get; set; }
        public Nullable<int> ContractEndDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> NextAppointmentDate { get; set; }
        public Nullable<System.TimeSpan> NextAppointmentTime { get; set; }
        public Nullable<bool> IsAppointmentFinished { get; set; }
        public Nullable<int> Payment { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
