//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyAccounting.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsBefore { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
